[package]
name = "shadow-reth"
description = "A single-node implementation of a Shadow RPC on top of Reth, utilizing ExEx and custom RPC methods."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
exclude.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# Shadow
shadow-reth-exex.workspace = true
shadow-reth-rpc.workspace = true

# Reth
reth.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-ethereum.workspace = true
reth-primitives.workspace = true
reth-tracing.workspace = true

# Crates
eyre.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
